- name: "Restart PHP-FPM"
  service:
    name: php5-fpm
    state: restarted

- name: "Reload PHP-FPM"
  service:
    name: php5-fpm
    state: reloaded

- name: "Restart Memcached"
  service: 
    name: memcached
    state: restarted

- name: "Reload Memcached"
  service: 
    name: memcached
    state: reloaded
